Description: CFN Template to update one of the two instances

Parameters:
  differentAMI:
    Description: Windows Server 2012 R2 Base
    Type: String



Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: AWS_KeyPair
      LaunchTemplateName: Two-EC2-Instances-Template-Lab5-1-2


  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref differentAMI
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: WindowsInstance

  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06878d265978313ca
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: UbuntuInstance