Description: CFN Template to create two instances

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: AWS_KeyPair
      LaunchTemplateName: Two-EC2-Instances-Template-Lab5-1-2


  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0db0a93f937948bf7
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: WindowsInstance

  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06878d265978313ca
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: UbuntuInstance